### ISSUE TITLE
addMany: template file `.gitignore.hbs`  not change filename to `.gitignore`

### ISSUE THREAD

**Issue by yunqiangwu** [plopjs/plop#320] opened 2022-03-08 11:38 UTC
## What happens?

addMany: template file `.gitignore.hbs`  not change filename to `.gitignore`

## source

https://github.com/plopjs/node-plop/blob/master/src/actions/addMany.js#L83-L95

**Comment by crutchcorn** [comment] 2022-04-27 04:38
Closing as a duplicate of #324

**Closed by crutchcorn** 2022-04-27 04:38 UTC
