### ISSUE TITLE
Is there a way to register Handlebars-helpers external libraries ?

### ISSUE THREAD

**Issue by afaucogney** [plopjs/plop#281] opened 2021-09-10 16:10 UTC
I saw this usefull set of helper. I didn't find a way to get the handlebars instance of plop to bind with this helper : https://github.com/helpers/handlebars-helpers

**Comment by MarioSchy** [comment] 2021-10-06 10:30
> I saw this usefull set of helper. I didn't find a way to get the handlebars instance of plop to bind with this helper : https://github.com/helpers/handlebars-helpers

I managed to include this helpers within my plop project, whereby I'm using Typescript for my plop file.

Here's the regarding code exerpt:

````typescript
function registerHandleBarHelpers(plop: NodePlopAPI): void {
    for (const prop in helpers) {
         // if it is not an already included "case" helper, than add the helper to plop
        if (!prop.toLowerCase().includes("case")) {
            plop.setHelper(prop, helpers[prop]);
        }
    }

    // overwrite "raw" helper afterwards, because it's not able to 
    // avoid escaping of {{{{raw}}}} block content otherwise
    plop.setHelper("raw", (options: Handlebars.HelperOptions) => {
        return options.fn(undefined);
    });
}
````

**Comment by crutchcorn** [comment] 2022-04-26 00:42
@MarioSchy has the answer here - closing since that's intended behavior

**Closed by crutchcorn** 2022-04-26 00:42 UTC
