### ISSUE TITLE
No plopfile found! - message after compilation in procedural script

### ISSUE THREAD

**Issue by konstantinB1** [plopjs/plop#386] opened 2023-06-09 13:37 UTC
When running a command:
`"generate:plop": "concurrently -g --names \"swc plopfile\\,generate api\" -g \"npx swc ./.build/rtkGenerator/plopfile.ts -o ./.build/rtkGenerator/plopfile.js\" \"plop --plopfile ./build/rtkGenerator/plopfile.js",
`
It results in error message, saying plopfile.js doesn't exist, even tho the file is there and the command runs after compilation.

# Expected behaviour
Run plopfile.js normally

# Actual behaviour
Error message: `No plopfile found!`

[Little more about the issue here
](https://github.com/plopjs/plop/issues/297#issuecomment-1584578316)

**Comment by crutchcorn** [comment] 2023-07-29 22:22
Do you have a minimal repro I can use to investigate? The linked issue is super broad and likely isn't the root cause of what you're experiencing.

**Comment by crutchcorn** [comment] 2023-09-04 09:36
Closing as there's no minimal repro

**Closed by crutchcorn** 2023-09-04 09:36 UTC
